config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/time_invoices/all', to: 'time_invoices#indexall' , as: :indexall
get '/time_invoices/all/new', to: 'time_invoices#topnew' , as: :topnew

match '/time_invoice_reports/index' => 'time_invoice_reports#index', via: [:get, :post]
match '/time_invoice_reports/report' => 'time_invoice_reports#report', via: [:get, :post]

match '/time_invoice_reports/:project_id/project_index' => 'time_invoice_reports#project_index', via: [:get, :post]
match '/time_invoice_reports/:project_id/project_report' => 'time_invoice_reports#project_report', via: [:get, :post]
get '/time_invoice_reports/:project_id/project_report' => 'time_invoice_reports#project_report'

match '/feed' => 'time_invoice_reports#feed',:as => :feed, :defaults => { :format => 'atom' }, via: [:get, :post]
match '/time_invoices/indexall' => 'time_invoices#indexall', via: [:get, :post]

match '/time_invoice_charts/index' => 'time_invoice_charts#index', via: [:get, :post]
match '/time_invoice_charts/:project_id/index_for_project' => 'time_invoice_charts#index_for_project', via: [:get, :post]
match '/time_invoice_charts/group' => 'time_invoice_charts#group', via: [:get, :post]
match '/time_invoice_charts/individual' => 'time_invoice_charts#individual', via: [:get, :post]

resources :projects, only: [] do
  resources :time_invoices
  resources :time_invoice_reports
end

resources :time_invoices
resources :time_invoice_reports #check index duplicate

app/models/time_invoice.rb
class TimeInvoice < ActiveRecord::Base
  unloadable
  belongs_to :project
  has_many :time_invoice_details, dependent: :destroy
  belongs_to :submitted_by, class_name: User.name   
  accepts_nested_attributes_for :time_invoice_details
  validate :correctness_of_date, :overlapping, :on=> :create
  after_save :notify_time_invoice_saved

  
  def build_time_invoice_details
    parent_project_id = self.project_id
    child_projects = Project.find(parent_project_id).descendants
    child_projects_id = []
    child_projects.each do |project_id|
      child_projects_id << project_id.id
    end
    projects_for_time_invoice = child_projects_id
    projects_for_time_invoice << parent_project_id
    
    user_hours = TimeEntry.group(:user_id).where(
      project_id: projects_for_time_invoice,
      spent_on: self.start_date..self.end_date
    ).sum(:hours)
    
    user_hours.each_pair do |user_id, hours|
      self.time_invoice_details.build(
        user_id: user_id,
        logged_hours: hours,
      )
    end
  end

  def notify_time_invoice_saved
    if self.submitted_by.nil?
      TimeInvoiceMailer.notify_time_invoice_generated(self).deliver
    
    else
        TimeInvoiceMailer.notify_time_invoice_submitted(self).deliver      
    end
  end
  private :notify_time_invoice_saved
  
  def correctness_of_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:Date_format, ": 'end date' less than 'start date' is not permitted")
    else
      errors.add(:start_date, "is required") if !start_date.present?
      errors.add(:end_date, "is required") if !start_date.present? 
    end
  end
  
  def overlapping
    time_invoices=TimeInvoice.where("project_id=? AND ((start_date<=? AND end_date>=?) OR (start_date<=? AND end_date>=?))", project_id,start_date,start_date,end_date,end_date)
    array_ids=time_invoices.collect{|ti| ti.id}

    
    if time_invoices.count>0 
      errors.add(:Overlapping, ":Time invoices cannot overlap,Change the date range")
    end
  end
end

app/controllers/time_invoices_controller.rb
class TimeInvoicesController < ApplicationController
  unloadable
    menu_item :time_invoices_all, :only => :indexall
    menu_item :time_invoices_top, :only => :topnew
    menu_item :time_invoices_index, :only => :index
    menu_item :time_invoices_new, :only => :new

  before_action :init_project
  if Redmine::Plugin.installed?(:redmine_contacts_invoices)
    include ContactsHelper
  end
  
  def init_project
    @project = params[:project_id] && Project.find(params[:project_id])
  end
  private :init_project
  
  def new
   
    return deny_access unless User.current.allowed_to?(:generate_time_invoices , @project)

    @time_invoice=TimeInvoice.new(:project_id => (@project && @project.id), 
      :start_date => (Date.today - 1.month).beginning_of_month, 
      :end_date => (Date.today-1.month).end_of_month)
  end
  
  def topnew
    return deny_access unless User.current.allowed_to_globally?(:submit_invoiceable_time ,{}) || 
      User.current.allowed_to_globally?(:generate_time_invoices , {}) ||
      User.current.allowed_to_globally?(:edit_invoiceable_time,{})
    @projects=projects_all
    return deny_access if @projects.empty?
    @time_invoice=TimeInvoice.new(:start_date => (Date.today-1.month).beginning_of_month,
      :end_date => (Date.today-1.month).end_of_month)
  end

  def index
    return deny_access unless User.current.allowed_to?(:submit_invoiceable_time , @project) || 
      User.current.allowed_to?(:generate_time_invoices , @project)
    
    @time_invoices = TimeInvoice.where(project_id: @project.id)
  end
  
  def indexall     
    return deny_access unless User.current.allowed_to_globally?(:submit_invoiceable_time ,{}) || 
      User.current.allowed_to_globally?(:generate_time_invoices , {}) ||
      User.current.allowed_to_globally?(:edit_invoiceable_time,{})
    time_invoices = TimeInvoice.includes(:project).all
#    @time_invoices = time_invoices.delete_if {|ti| (!User.current.allowed_to?(:submit_invoiceable_time , ti.project) &&
#          !User.current.allowed_to?(:generate_time_invoices , ti.project) &&
#          !User.current.allowed_to?(:edit_invoiceable_time, ti.project)
#      )}
    @time_invoices = time_invoices.to_a.delete_if {|ti| (!User.current.allowed_to?(:submit_invoiceable_time , ti.project) &&
          !User.current.allowed_to?(:generate_time_invoices , ti.project) &&
          !User.current.allowed_to?(:edit_invoiceable_time, ti.project)
      )}
  end
  
  def create
#    @time_invoice = TimeInvoice.new(params[:time_invoice])
    @time_invoice = TimeInvoice.new(permit_generate_invoice_params)
    if @time_invoice.save
      unless params[:project_id].nil?
        redirect_to :controller => 'time_invoices', :action=> 'index',
          :project_id=>params[:project_id]
      else
        redirect_to :indexall, :flash=>{:notice=> 'Time invoice has been successfully created!'}
      end
    else
      unless params[:project_id].blank?
        init_project
        render 'new'
      else
        @projects=projects_all
        return deny_access if @projects.empty?
        render 'topnew'
      end
    end
  end
  def allowed_to_submit?(time_invoice)
    return true if User.current.allowed_to? :edit_invoiceable_time, time_invoice.project
    return false if time_invoice.submitted_by_id.present?
    return false unless User.current.allowed_to? :submit_invoiceable_time, time_invoice.project
    return true
  end

  def edit
    @time_invoice = TimeInvoice.includes(:project).find(params[:id])
    return deny_access unless allowed_to_submit?(@time_invoice)
    
    unless @time_invoice.submitted_by_id.present?
      @time_invoice.build_time_invoice_details
    end
  end
  
  def update
       
    @time_invoice = TimeInvoice.find(params[:id])
    return deny_access unless allowed_to_submit?(@time_invoice)
#    if @time_invoice.update_attributes(params[:time_invoice])
    if @time_invoice.update(permit_time_invoice_params)
      if Setting.plugin_redmine_time_invoices['billing_invoice'] && Redmine::Plugin.installed?(:redmine_contacts_invoices)        
        unless @time_invoice.invoice_id.present?
          billing_invoice = Invoice.
            create!(number: "Invoice-#{Time.now.strftime("%Y%m%d%H%M%S")}",
            invoice_date: DateTime.now, project_id: @time_invoice.project_id, status_id: 1)
          billing_invoice.lines.build(quantity: @time_invoice.time_invoice_details.sum(:invoiced_quantity),
            description: "Billing Invoice")        
          billing_invoice.save!
          @time_invoice.invoice_id = billing_invoice.id
          @time_invoice.save!
        else
          billing_invoice = Invoice.find(@time_invoice.invoice_id)
          billing_invoice.lines.first.quantity = @time_invoice.time_invoice_details.sum(:invoiced_quantity)          
          billing_invoice.lines.first.save!
        end        
      end
      redirect_to :controller => 'time_invoices', :action=> 'show',:id=>@time_invoice.id,
        :project_id=>params[:project_id]
    else
      unless params[:project_id].nil?
        init_project
      end
      render 'edit'
    end
  
  end
  def show
    @time_invoice = TimeInvoice.find(params[:id])
    return deny_access unless User.current.allowed_to?(:submit_invoiceable_time , @time_invoice.project) || 
      User.current.allowed_to?(:generate_time_invoices , @time_invoice.project)
  end
  def projects_all
    projects=Project.all
#    projects.delete_if {|project| !User.current.allowed_to?(:generate_time_invoices , project)}
    projects.to_a.delete_if {|project| !User.current.allowed_to?(:generate_time_invoices , project)}
  end
  
  private
  def permit_time_invoice_params
    params.require(:time_invoice).permit(:submitted_by_id, :comment, 
      time_invoice_details_attributes: [:user_id, :invoiced_quantity, :invoiced_unit, :comment])
  end
  
  def permit_generate_invoice_params
    params.require(:time_invoice).permit(:project_id, :start_date, :end_date, :submitted_by_id, :comment)
  end
end

app/helpers/time_invoices_helper.rb
module TimeInvoicesHelper
end

app/views/time_invoices/_form.html.erb
<h2>Update time invoice</h2>
<div class="box tabular">
  <%= form_for [@project, @time_invoice] do |f|%>
    <% if @time_invoice.errors.any? %>
      <% flash.now[:error] = "#{pluralize(@time_invoice.errors.count, "error")} prohibited
    this post from being updated: <br/>" %>
      <ul>
        <% @time_invoice.errors.full_messages.each do |msg| %>
          <% flash.now[:error] += "<li>#{msg}</li>" %>
        <% end %>
      </ul>
    <% end %>
    <h3><%= @time_invoice.project.name %></h3><br/>
    <p> <%=f.label :start_date %><br/>
      <%=f.date_select :start_date, disabled: true%>
    </p>
    <p>
      <%=f.label :end_date%><br/>
      <%=f.date_select :end_date, disabled: true%>
    </p>
    <%=  f.hidden_field :submitted_by_id, :value=> User.current.id%>
    <p> 
      <%= f.label :comment %><br/>
      <%=f.text_area :comment, :size => "60x3"%>
    </p>
    <%if @time_invoice.time_invoice_details.empty?%>
      <%='No activity performed yet'%>
    <%else%>
      <%= render partial: 'time_invoice_details/fields_table', 
        locals: {time_invoice_form: f} %>
    <%end%>  
  </div>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/time_invoices/edit.html.erb
<%= render partial: 'form'%>

app/views/time_invoices/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'timeinvoice-menu', :plugin => 'redmine_time_invoices' %>
  <% end %>

<div id="timeinvoice-menu">
     <%= render_menu(:time_invoices_menu_project)%>
</div>

<h3>List of Time Invoices for <%= @project.name%></h3>
<%  id=@project.id%>
<%#= link_to 'Generate a new invoice', :controller=>'time_invoices',:action=>'new',:project_id=>@project.id%><br/>
<%#= link_to 'View Time Invoice Report', :controller=>'time_invoice_reports',:action=>'project_index',:project_id=>@project.id%><br/><br/>
<% if @time_invoices.empty? %>
<br/><label><%= 'No TimeInvoices to show yet' %></label>
<%else%>
  <table border="1">
    <tr><th>ID</th><th>Start Date</th> <th>End Date</th> <th>Invoice Submitter</th> <th>Project Name</th> <th>Remarks</th> <th>Action</th></tr>
    <%  @time_invoices.each do |ti| %>
      <tr>
        <td>
          <%=  ti.id%>
        </td>
        <td>
          <%=  ti.start_date%>
        </td>
        <td>
          <%=  ti.end_date%>
        </td>
        <td>
          <%=  ti.submitted_by && ti.submitted_by.name%>
        </td>
        <td>
          <%=  ti.project.name %>
        </td>
        <td>
          <%=  ti.comment %>
        </td>
        <%if ti.submitted_by %>
        <td>
          <%=  link_to 'View', [ti.project, ti]%>
         </td>
        <%else%>
        <td>
          <%=  link_to 'Edit/Submit', edit_project_time_invoice_path(ti.project, ti) %>
         </td>
        <%end%>
      </tr>
    <%end%>
 </table>      
<%end%>
      
 

app/views/time_invoices/indexall.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'timeinvoice-menu', :plugin => 'redmine_time_invoices' %>
<% end %>

<% if User.current.allowed_to_globally?(:generate_time_invoices, {}) %>
  <div id="timeinvoice-menu">
    <%= render_menu(:time_invoices_menu)%>
  </div>
  <% end %>

<h3>List of Time Invoices</h3>

  <% if @time_invoices.empty? %>
    <br/><label><%= 'No TimeInvoices to show yet' %></label>
  <%else%>
    <table border="1">
      <tr><th>ID</th><th>Start Date</th> <th>End Date</th> 
        <th>Invoice Submitter</th> <th>Project Name</th> <th>Remarks</th>
        <th>Action</th>
      </tr>
      <%  @time_invoices.each do |ti| %>      
        <tr>
          <td>
            <%=  ti.id%>          
          </td>
          <td>
            <%=  ti.start_date%>
          </td>
          <td>
            <%=  ti.end_date%>
          </td>
          <td>
            <%=  ti.submitted_by && ti.submitted_by.name%>
          </td>
          <td>
            <%=  ti.project.name %>
          </td>
          <td>
            <%=  ti.comment %>
          </td>
          <%if ti.submitted_by %>
            <td>
              <%=  link_to 'View', ti%>
              <% if User.current.allowed_to? :edit_invoiceable_time, ti.project %>
                | <%=  link_to 'Edit/Submit', edit_time_invoice_path(ti) %>
              <% end %>
            </td>
          <%else%>
            <td>
              <% if User.current.allowed_to?(:submit_invoiceable_time, ti.project) %>
                <%=  link_to 'Edit/Submit', edit_time_invoice_path(ti) %>
              <% end %>
            </td>
          <%end%>          
        </tr>
      <%end%>
    </table>
  <%end%>

app/views/time_invoices/new.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'timeinvoice-menu', :plugin => 'redmine_time_invoices' %>
  <% end %>

<div id="timeinvoice-menu">
     <%= render_menu(:time_invoices_menu_project)%>
</div>

<%= form_for [@project, @time_invoice] do |f|%>
  <% if @time_invoice.errors.any? %>

      <% flash.now[:error] = "#{pluralize(@time_invoice.errors.count, "error")} prohibited
    this invoice from being saved: <br/>" %>
      <ul>
        <% @time_invoice.errors.full_messages.each do |msg| %>
          <% flash.now[:error] += "<li>#{msg}</li>" %>
        <% end %>
      </ul>
    <% end %>
    <h3>Generate New Invoice for <%= @project.name %></h3><br/>
    <p> <%= f.label :start_date %><br/>
      <%= f.text_field :start_date%>
      <%= calendar_for 'time_invoice_start_date'%>
    </p>
    <p>
      <%= f.label :end_date%><br/>
      <%= f.text_field :end_date%>
      <%= calendar_for 'time_invoice_end_date'%>
    </p>
    <%=  f.hidden_field :submitted_by_id, :value=> nil%>
    <%=  f.hidden_field :project_id, :value=> @project.id%>
    <p>
      <%= f.label :comment %><br/>
      <%= f.text_area :comment, :size => "60x3"%>
    </p>
  </div>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/time_invoices/show.html.erb
<h3><%="TimeInvoice for #{@time_invoice.project.name}"%></h3>
<div class="box tabular">
  <%="For Duration of #{@time_invoice.start_date} -  #{@time_invoice.end_date}"%><br/>
  <%unless @time_invoice.submitted_by.nil?%>
    <strong><%="Submitted By #{@time_invoice.submitted_by.name}"%></strong><br/>
  <%end%>
  <%unless @time_invoice.comment.blank?%>
    <strong><%='Remarks:'%><br/></strong><%=@time_invoice.comment%><br/>
  <%end%>
  <%unless @time_invoice.time_invoice_details.empty?%>
    <table class="list issue">
      <%time_invoice_detail=@time_invoice.time_invoice_details%>
      <tr>
        <th>User</th>
        <th>Logged hours</th>
        <th>Invoiced hours</th>
        <th>comments</th>
      </tr>
      <%time_invoice_detail.each do |details|%>
        <tr class="<%= cycle("odd", "even")%> issue">
          <td><%= link_to details.user.name,user_path(details.user.id)%></td>
          <td><%=details.logged_hours%></td>
          <td><%=details.invoiced_hours%></td>
          <td><%=details.comment%></td>
        </tr>
      <%end%>
    </table>
  <%end%>
</div>

app/views/time_invoices/topnew.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'timeinvoice-menu', :plugin => 'redmine_time_invoices' %>
  <% end %>

<div id="timeinvoice-menu">
     <%= render_menu(:time_invoices_menu)%>
</div>

<h3>Generate New Time Invoice </h3>

<%= form_for [@time_invoice] do |f|%>
  <% if @time_invoice.errors.any? %>

      <% flash.now[:error]= "#{pluralize(@time_invoice.errors.count, "error")} prohibited
    this invoice from being saved: <br/>" %>
      <ul>
        <% @time_invoice.errors.full_messages.each do |msg| %>       
          <% flash.now[:error] += "<li>#{msg}</li>" %>
        <% end %>
      </ul>
    <% end %>
    <%=  f.select :project_id,options_for_select(@projects.collect{|u| [u.name,u.id]})%>
    <p> <%= f.label :start_date %><br/>
      <%= f.text_field :start_date%>
      <%= calendar_for 'time_invoice_start_date'%>
    </p>
    <p>
      <%= f.label :end_date%><br/>
      <%= f.text_field :end_date%>
      <%= calendar_for 'time_invoice_end_date'%>
    </p>
    <%=  f.hidden_field :submitted_by_id, :value=> nil%>
    <p>
      <%= f.label :comment %><br/>
      <%= f.text_area :comment, :size => "60x3"%>
    </p>
  </div>
  <p>
    <%= f.submit %>
  </p>
<%end%>